version: '3'

services:
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi
    ports:
      - 3000:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=admin@docker.yapi
      - YAPI_ADMIN_PASSWORD=adm1n
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=mongo-yapi
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - mongo-yapi
    networks:
      - yapi
    restart: unless-stopped
  mongo-yapi:
    image: mongo:3.6.21-xenial
    container_name: mongo-yapi
    volumes:
      - mongo-yapi:/data/yapi-mongo
    expose:
      - 27017
    restart: unless-stopped
    networks:
      - yapi
networks:
  yapi:
    external: true
